# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12W4aXjK06wAUtOU6pXYJAlnVX5Bt3dQL

**Task 06: Modifying RDF(s)**
"""


github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

ns = Namespace("http://somewhere#")

g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

ns = Namespace("http://somewhere#")
fullName = Literal("Jane Smithers")
EX = Namespace("http://example.org/")
janeURI = EX.JaneSmithers
resource = (janeURI, RDF.type, ns.Researcher)
g.add((resource))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

schema = Namespace("https://schema.org")
ns = Namespace("http://somewhere#")
g.add((janeURI, schema.email, Literal("jane.smithers@example.com")))
g.add((janeURI, schema.name, Literal("Jane Smithers")))
g.add((janeURI, schema.givenName, Literal("Jane")))
g.add((janeURI, schema.familyName, Literal("Smithers")))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

EX = Namespace("https://example.org/")
johnname = Literal("John Smith")
johnURI = EX.johnname
UPM = EX.Literal("UPM")
g.add((johnURI, EX.worksAt, UPM))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

from rdflib import FOAF
johnname = Literal("John Smith")
johnURI = EX.johnname
EX = Namespace("https://example.org/")
g.add((johnURI, FOAF.knows, janeURI))
for s, p, o in g:
  print(s,p,o)


# The script's been done on collab, it may contain repetitive code